collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5574468
color:
  saturation: 0.09936521
  brandStrength: 0.8042553
  rhythmicContrast: 0.9950004
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#7E7E7E'
    - '#BFBFBF'
    - '#444444'
  lightness: 0.02495512
layout_spectrum: 0.5448028
name: RGentileGallery
