layout_spectrum: 0.4525954
typography_spectrum: 0.4851359
color:
  saturation: 0.09936521
  lightness: 0.02495512
  brandStrength: 0.727203
  rhythmicContrast: 0.9950004
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: RGentileGallery
